### ISSUE TITLE
Ignore custom image sizes on uplaod

### ISSUE THREAD

**Issue by EdwardBock** [palasthotel/image-sizes-on-demand#6]
We can improve upload performance for themes with logs of image sizes if we ignore custom image sizes and only let wordpress generate the core image sizes on media upload.

**Comment by EdwardBock** [comment]
If it is urgent I'll do it myselfe else I will try to ask @JuliaKrischik for her time :)

**Comment by juliakleinediekmann** [comment]
Done. @EdwardBock update should show up in WordPress within the next few minutes.
